"""Add image_data columns

Revision ID: 0afb8bb81843
Revises: 79205306c27b
Create Date: 2026-02-15 01:37:04.654224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afb8bb81843'
down_revision: Union[str, Sequence[str], None] = '79205306c27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('gallery_images', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('menu_items', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('special_offers', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_offers', 'image_data')
    op.drop_column('menu_items', 'image_data')
    op.drop_column('gallery_images', 'image_data')
    op.drop_column('categories', 'image_data')
    # ### end Alembic commands ###
