"""add_image_data_columns_nullable

Revision ID: 26f2df0cb9d5
Revises: 0afb8bb81843
Create Date: 2026-02-15 02:49:37.502656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f2df0cb9d5'
down_revision: Union[str, Sequence[str], None] = '0afb8bb81843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gallery_images', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gallery_images', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
