"""add auth0_id to users

Revision ID: 47682d64ce7e
Revises: 4bdd07877393
Create Date: 2026-03-02 15:24:28.024198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47682d64ce7e'
down_revision: Union[str, Sequence[str], None] = '4bdd07877393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['auth0_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###
