"""Add special_offer_id to order_items

Revision ID: 49b2b7359135
Revises: 7fb28d78e379
Create Date: 2026-03-02 19:19:20.018567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b2b7359135'
down_revision: Union[str, Sequence[str], None] = '7fb28d78e379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('special_offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'special_offers', ['special_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'special_offer_id')
    # ### end Alembic commands ###
