"""Add address to users

Revision ID: 7fb28d78e379
Revises: 47682d64ce7e
Create Date: 2026-03-02 17:37:05.228845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb28d78e379'
down_revision: Union[str, Sequence[str], None] = '47682d64ce7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_auth0_id_key'), 'users', type_='unique')
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_auth0_id_key'), 'users', ['auth0_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
